{{- if .Values.puppetserver.masters.ingress.enabled -}}
{{- $releaseName := .Release.Name -}}
{{- $serviceName := include "puppetserver.puppetserver-masters.serviceName" . }}
{{- $servicePort := .Values.puppetserver.masters.service.ports.puppetserver.port -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  {{- if .Values.puppetserver.masters.ingress.annotations }}
  annotations:
    {{ toYaml .Values.puppetserver.masters.ingress.annotations | nindent 4 }}
  {{- end }}
  labels:
    {{- include "puppetserver.puppetserver.labels" . | nindent 4 }}
    {{- range $key, $value := .Values.puppetserver.masters.ingress.extraLabels }}
    {{ $key }}: {{ $value }}
    {{- end }}
  name: {{ template "puppetserver.fullname" . }}-masters
spec:
  rules:
    {{- range .Values.puppetserver.masters.ingress.hosts }}
    {{- $url := splitList "/" . }}
    - host: {{ first $url }}
      http:
        paths:
          - path: /{{ rest $url | join "/" }}
            backend:
              serviceName: {{ $serviceName }}
              servicePort: {{ $servicePort }}
    {{- end -}}
  {{- if .Values.puppetserver.masters.ingress.tls }}
  tls:
    {{ toYaml .Values.puppetserver.masters.ingress.tls | nindent 4 }}
  {{- end -}}
{{- end -}}
